<?php

/**
 * WordPress database error drop-in, installed by alptis/bedrock-db-error-page.
 *
 * WordPress loads this file (WP_CONTENT_DIR/db-error.php) instead of its own error message when the
 * database is unavailable:
 *
 *   - wpdb::db_connect() when the connection fails,
 *   - dead_db() when the database selection fails or when the connection is lost.
 *
 * It renders custom_db_error.html (located next to this file) with a 503 status. Unlike db.php, it does
 * not replace the global $wpdb object, so it stays compatible with any plugin providing its own db.php
 * drop-in (Query Monitor, HyperDB, LudicrousDB...).
 *
 * Do not edit this file: it is overwritten on every `composer install` and `composer update`.
 * Customize custom_db_error.html instead, which is never overwritten.
 *
 * @see wp-includes/class-wpdb.php::db_connect()
 * @see wp-includes/functions.php::dead_db()
 */

// Required from wpdb::db_connect() ($this) or from dead_db() (local $wpdb).
$bedrockDb = (isset($this) && $this instanceof wpdb) ? $this : ($wpdb ?? null);

$databaseErrorReadon = ($bedrockDb && $bedrockDb->dbh instanceof mysqli)
    ? 'database selection failed: ' . (mysqli_error($bedrockDb->dbh) ?: 'unknown error')
    : 'connection failed: ' . (mysqli_connect_error() ?: 'unknown error');

error_log('[alptis/bedrock-db-error-page] Database ' . $databaseErrorReadon);

// On the healthcheck endpoints only, let alptis/wordpress-healthcheck answer with its JSON report
// instead of the error page. Every other request gets the error page below.
// The reason holds the raw database error: the healthcheck only logs it and never displays it.
$bedrockHealthchecker = 'Alptis\\Wordpress\\Healthcheck\\Healthchecker';
$bedrockDatabaseCheck = 'Alptis\\Wordpress\\Healthcheck\\WordpressDatabaseCheck';
$bedrockHealthcheckInstalled = class_exists($bedrockHealthchecker)
    && class_exists($bedrockDatabaseCheck)
    && method_exists($bedrockHealthchecker, 'isHealthcheckRequest')
    && method_exists($bedrockDatabaseCheck, 'handleConnectionFailure');

if ($bedrockHealthcheckInstalled && $bedrockHealthchecker::isHealthcheckRequest()) {
    $bedrockDatabaseCheck::handleConnectionFailure($databaseErrorReadon);
}

if (!headers_sent()) {
    http_response_code(503);
    header('Content-Type: text/html; charset=utf-8');
    header('Retry-After: 600');
    header('Cache-Control: no-cache, no-store, must-revalidate');
}
require __DIR__ . '/custom_db_error.html';
exit;
